Description: "AWS CloudFormation Template for Amazon DocumentDB"

Parameters: 
  DBClusterName: 
    Default: "DocumentDBCluster"
    Description: "Cluster name"
    Type: "String"
    MinLength: "1"
    MaxLength: "64"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*"
    ConstraintDescription: "Must begin with a letter and contain only alphanumeric characters."

  DBInstanceName: 
    Default: "DocumentDBInstance"
    Description: "Instance name"
    Type: "String"
    MinLength: "1"
    MaxLength: "64"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*"
    ConstraintDescription: "Must begin with a letter and contain only alphanumeric characters."

  MasterUser:
    Default: "admin1"
    NoEcho: true
    Description: "The database admin account username"
    Type: "String"
    MinLength: "1"
    MaxLength: "16"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "Must begin with a letter and contain only alphanumeric characters."

  DBInstanceClass:
    Default: "db.t3.medium"
    Description: "Instance class. Please refer to: https://docs.aws.amazon.com/documentdb/latest/developerguide/db-instance-classes.html#db-instance-classes-by-region"
    Type: "String"
    AllowedValues:
      - db.t3.medium
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.12xlarge
      - db.r5.24xlarge                             
    ConstraintDescription: "Instance type must be one of the supported values for the region. Please refer to: https://docs.aws.amazon.com/documentdb/latest/developerguide/db-instance-classes.html#db-instance-classes-by-region"

  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: "The VPC where DocumentDB will be deployed"

  AllowedSecurityGroupId:
    Type: "AWS::EC2::SecurityGroup::Id"
    Description: "Security Group ID of the Lambda function or other resources that need to access DocumentDB"

Resources:
  DocumentDBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group for Amazon DocumentDB allowing inbound traffic from allowed resources"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          SourceSecurityGroupId: !Ref AllowedSecurityGroupId
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"

  CloudFormationCreatedSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: "Simple secret created by AWS CloudFormation."
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${MasterUser}"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludePunctuation: true

  DBCluster:
    Type: "AWS::DocDB::DBCluster"
    DeletionPolicy: Delete
    Properties:
      DBClusterIdentifier: !Ref DBClusterName
      MasterUsername: !Ref MasterUser
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${CloudFormationCreatedSecret}:SecretString:password}}'
      EngineVersion: 4.0.0
      VpcSecurityGroupIds:
        - !Ref DocumentDBSecurityGroup 

  DBInstance:
    Type: "AWS::DocDB::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceIdentifier: !Ref DBInstanceName
      DBInstanceClass: !Ref DBInstanceClass
    DependsOn: DBCluster

Outputs:
  ClusterId:
    Value: !Ref DBCluster
  ClusterEndpoint:
    Value: !GetAtt DBCluster.Endpoint
  ClusterPort:
    Value: !GetAtt DBCluster.Port
  EngineVersion:
    Value: "4.0.0"
  DocumentDBSecurityGroupId:
    Value: !Ref DocumentDBSecurityGroup
    Description: "The Security Group ID for DocumentDB"
    Export:
      Name: "TicketBookingDocumentDbSg"
