AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS Cluster and Networking for Ticket Booking Workflow Deployment"

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: "TicketBookingEcsCluster"

Outputs:
  ClusterName:
    Value: !Ref ECSCluster
    Export:
      Name: "TicketBookingEcsClusterName"
  ClusterArn:
    Description: "ECS Cluster ARN"
    Value: !GetAtt ECSCluster.Arn
    Export:
      Name: "TicketBookingEcsClusterArn"
