name: Deploy Booking Service Stack

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: "Select branch to deploy"
        required: true
        default: "master"

jobs:
  info:
    name: Info
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Details
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Git Branch: ${{ github.ref }}"
          echo "Git SHA: ${{ github.sha }}"
          echo "Github Event: ${{ github.event_name }}"

  deploy:
    name: Deploy AWS CDK Stack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install AWS CDK
        run: npm i -g aws-cdk

      - name: Install Dependencies
        run: npm i
        working-directory: booking-service

      - name: Validate CloudFormation Template
        run: cdk synth --app "npx ts-node bin/booking-service.ts"
        working-directory: booking-service

      - name: Run Jest Tests
        run: npm test
        working-directory: booking-service

      - name: Deploy Booking Service Stack
        run: cdk deploy --app "npx ts-node bin/booking-service.ts" --require-approval never
        working-directory: booking-service
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          CDK_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
